# Generated by Django 3.0.2 on 2020-01-14 12:53

from django.db import migrations


def insert_data(apps, schema_editor):
    InstitutionType = apps.get_model('donations', 'InstitutionType')
    InstitutionType.objects.create(id=1, type='fundacja')
    InstitutionType.objects.create(id=2, type='organizacja pozarządowa')
    InstitutionType.objects.create(id=3, type='zbiórka lokalna')


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20200114_1353'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
