# Generated by Django 3.0.2 on 2020-01-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20200114_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='donations.InstitutionType', verbose_name='rodzaj instytucji'),
        ),
    ]
