# Generated by Django 3.0.2 on 2020-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200114_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiontype',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='institutiontype',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Rodzaj instytucji'),
        ),
    ]
