# Generated by Django 3.0.2 on 2020-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20200114_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
